### ISSUE TITLE
Docs for preference modules

### ISSUE THREAD

**Issue by jscti** [MFlisar/ComposeChangelog#1]
Hi

I'll try to migrate to your compose version ^^

But could you improve your docs for the "module" section ?
Ok for the "core" one, but what about the 2 "preferences" ? Need both ? need to choose one ? What are the differences, how to choose ?

```
implementation("com.github.MFlisar.ComposeChangelog:statesaver-preferences:$composechangelog")
implementation("com.github.MFlisar.ComposeChangelog:statesaver-kotpreferences:$composechangelog")
```

An other question: Will I be able to open changelog popup from a non-Compose activity with this "compose" lib ? I have a legacy "PreferenceFragmentCompat" where I have a "show full changelog" button. And I don't want to compose-refactor it yet (yeah I saw your other lib ^^)

Thanks

**Comment by MFlisar** [comment]
**Preferences**
Check out following library: [KotPreferences](https://mflisar.github.io/github-docs/pages/libraries/kotpreferences/)
If you want to use it in combination with `ComposeChangelog` use the `statesaver-kotpreferences` module otherwise use the `statesaver-preferences` module or use non of them and implement the required interface however you want yourself ([IChangelogStateSaver](https://github.com/MFlisar/ComposeChangelog/blob/main/library/core/src/main/java/com/michaelflisar/composechangelog/interfaces/IChangelogStateSaver.kt)) - all the implementations do is loading and saving a single value (the last app version for which the changelog has been shown)

**Non compose usage**
I've never tried it but generally you can use compose inside a view based activity as well (https://developer.android.com/jetpack/compose/migrate/interoperability-apis/compose-in-views). Sadly I can't help you with that.

**Comment by jscti** [comment]
Thanks

I still don't get the 2 modules in the context of the changelog lib

```
val changelogStateSaver = ChangelogStateSaverPreferences(LocalContext.current)
val changelogStateSaverKotPrefs = ChangelogStateSaverKotPreferences(AppPrefs.lastShownVersionForChangelog)
```

Why would I need (or not) the KOT one over the non-kot one ? If i already use your KOT lib outside changelog lib ?
For a new user coming on your lib page (without knowing your other existing libs), it's quite confusing (even after reading kotPref page, which i Did).

**Comment by MFlisar** [comment]
> If i already use your KOT lib outside changelog lib ?

Because of this or to avoid using another preference file for just a single value (`ChangelogStateSaverPreferences` does simply do that).
